version: '3'
services:
  arangodb:
    image: arangodb:3.7
    restart: always
    env_file: ./vars.env
    volumes:
      - ./data:/var/lib/arangodb3
  epilyon_server:
    image: epilyon_server
    build: ./epilyon_server
    restart: always
    env_file: ./vars.env
    volumes:
      - ./config:/config
      - ./logs:/logs
    ports:
      - "127.0.0.1:7899:7899"
    depends_on:
      - "arangodb"